server:
  port: 8000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

mybatis-plus:
  configuration:
    # 关闭二级缓存
    cache-enabled: false
    # 设置本地缓存作用域
    local-cache-scope: SESSION

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false
#  pid:
#    file: /自行指定位置/eladmin.pid

  redis:
    #数据库索引
    database: ${REDIS_DB:1}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAoIU0g5iT/PraHSlw7HaPVDzwxkP9Hcyx80/QD9gxdQbOR6Qv+4sPBJOzdIHGnxWfEm8OH2kNJJeGRtMv6RwiMwIDAQABAkEAgj8zeif+xIHjI1Bx8VzONeLw119pbZmfNrcnMwQQNUyUL8dRXwWkVo5PA3J/URwxZORX91fgCjjtdlYBSoLwaQIhANLjh9GuZDuKmdmuuI7OJ3NvKns/l+NMgnAXoiyTOmXtAiEAwttzQLKg1UuVhtOeisUdM6/Bxma2yjdR8X/iIrdXpJ8CIQCHGTvpF88eVaw5x7Rzx51+VbjhO9wRwPHO3VUHOUowAQIgM/IKrIGyLIpkxzec+UOJAGFnV/vD2O6ccrPz1etoeuMCIQDQ+uHgv4VaINakyS+yfar+/NPIvMWVz6+/Ii3crY8OFA==